name: Run npm audit weekly

on:
  schedule:
  # UTC
  - cron: '0 14 * * 5'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.15]
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: save cache
      uses: actions/cache@v1
      with:
        path: node_modules
        key: v1-dependencies-{{ checksum "./package.json" }}
        restore-keys: |
          v1-dependencies-{{ checksum "./package.json" }}
    - name: npm install
      run: |
        npm ci
    - name: npm audit
      run: |
        npm audit
    - name: Slack Notification
      if: failure()
      uses: homoluctus/slatify@master
      with:
        type: ${{ job.status }}
        job_name: "*Check Vulnerability*"
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
